### ISSUE TITLE
ДЗ на проверку "Homework-2-Car-mileage"

### ISSUE THREAD

**Issue by Andreal79** [Andreal79/Homework-2-Car-mileage#1]
@coursar , добрый день, высылаю ДЗ на проверку

**Comment by coursar** [comment]
Исправить #2, #3, #4, после чего переоткрыть Issue.

**Comment by Andreal79** [comment]
@coursar , добрый день, исправил #2, #3, #4, высылаю ДЗ на проверку

**Comment by coursar** [comment]
Ключевые моменты:
1. Желательно одним коммитом закрывать только один issue
2. Нужно писать fixes #1, fixes #2 и т.д., чтобы они закрывались.

Т.е. если что-то сделали - закрывайте issue.
